import "./globals.css";
import { Inter } from "next/font/google";
import { MantainProvides } from "./mantainProvider";
import { ReduxProvider } from "./provider";
import HomeLayout from "./homeLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Miss Cire Quiz",
  description: "Generated by miss cire",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantainProvides>
          <ReduxProvider>
            <HomeLayout>{children}</HomeLayout>
          </ReduxProvider>
        </MantainProvides>
      </body>
    </html>
  );
}
